import type { ContentAsset } from "@/types/dashboard";

export const contentSummary = [
  { label: "All assets", value: "1,248", active: true },
  { label: "Movies", value: "342" },
  { label: "Series & episodes", value: "618" },
  { label: "Music", value: "241" },
  { label: "Trailers", value: "47" },
] as const;

export const contentAssets: ContentAsset[] = [
  {
    id: "lagos-after-dark",
    title: "Lagos After Dark",
    subtitle: "Featured film · 1h 52m",
    type: "Movie",
    typeTone: "purple",
    genre: "Thriller",
    status: "Ready",
    dateAdded: "10 Apr 2026",
    views: "201K",
    swatch: "#161D2D",
    description: "A gripping thriller set in the heart of Lagos.",
    releaseDate: "27/03/2026",
    cast: "Chisom Nwosu, Bayo Ola, Amina Diallo",
    subtitleFile: "lagos-after-dark-en.srt",
  },
  {
    id: "kings-lagos-s01e01",
    title: "Kings of Lagos",
    subtitle: "S01E01 — Pilot",
    type: "Series",
    typeTone: "purple",
    genre: "Drama",
    status: "Error",
    dateAdded: "11 Apr 2026",
    views: "412K",
    swatch: "#26254E",
    description: "Pilot episode introducing Lagos power families.",
    releaseDate: "27/03/2026",
    cast: "Tobi Adeyemi, Zainab Balogun",
    subtitleFile: "kings-of-lagos-s01e01-en.srt",
  },
  {
    id: "afrobeats-vibes-vol-3",
    title: "Afrobeats Vibes Vol. 3",
    subtitle: "DJ Mix · 1h 12m",
    type: "DJ Mix",
    typeTone: "cyan",
    genre: "Afrobeats",
    status: "Ready",
    dateAdded: "16 Apr 2026",
    views: "285K",
    swatch: "#214A7C",
    description: "A long-form DJ mix featuring the biggest Afrobeats tracks of the year.",
    releaseDate: "27/03/2026",
    cast: "DJ Kobby",
    subtitleFile: "afrobeats-vibes-vol-3-en.srt",
  },
  {
    id: "jollof-dreams",
    title: "Jollof Dreams",
    subtitle: "S02E01 — New Beginnings",
    type: "Episode",
    typeTone: "purple",
    genre: "Comedy",
    status: "Ready",
    dateAdded: "13 Apr 2026",
    views: "—",
    swatch: "#352052",
    description: "A comedy series episode set around a family-owned restaurant.",
    releaseDate: "13/04/2026",
    cast: "Adaeze Onuoha, Teniola Alabi",
    subtitleFile: "jollof-dreams-s02e01-en.srt",
  },
  {
    id: "motherland",
    title: "Motherland",
    subtitle: "Album · 14 tracks",
    type: "Album",
    typeTone: "blue",
    genre: "Afropop",
    status: "Ready",
    dateAdded: "10 Apr 2026",
    views: "327K",
    swatch: "#1C371B",
    description: "A 14-track exploration of African identity, roots and diaspora culture.",
    releaseDate: "27/03/2026",
    cast: "Burna Boy",
    subtitleFile: "motherland-lyrics.srt",
  },
  {
    id: "nairobi-nights-trailer",
    title: "Nairobi Nights",
    subtitle: "Official Trailer · 2m 18s",
    type: "Trailer",
    typeTone: "gray",
    genre: "Drama",
    status: "Ready",
    dateAdded: "17 Apr 2026",
    views: "12K",
    swatch: "#4A2320",
    description: "Trailer for Nairobi Nights.",
    releaseDate: "17/04/2026",
    cast: "N/A",
    subtitleFile: "nairobi-nights-trailer-en.srt",
  },
  {
    id: "kings-lagos-s01e02",
    title: "Kings of Lagos",
    subtitle: "S01E02 — The Deal",
    type: "Movie",
    typeTone: "purple",
    genre: "Drama",
    status: "Error",
    dateAdded: "19 Apr 2026",
    views: "512K",
    swatch: "#6C2151",
    description: "Follow-up episode with a failed transcode pending replacement.",
    releaseDate: "19/04/2026",
    cast: "Ensemble",
    subtitleFile: "kings-of-lagos-s01e02-en.srt",
  },
  {
    id: "highlife-reborn",
    title: "Highlife Reborn",
    subtitle: "Album · 9 tracks",
    type: "Album",
    typeTone: "blue",
    genre: "Highlife",
    status: "Error",
    dateAdded: "15 Apr 2026",
    views: "17K",
    swatch: "#315B5F",
    description: "Highlife compilation with pending processing correction.",
    releaseDate: "15/04/2026",
    cast: "Various Artists",
    subtitleFile: "highlife-reborn-lyrics.srt",
  },
  {
    id: "accra-by-night",
    title: "Accra by Night",
    subtitle: "Feature film · 2h 04m",
    type: "Movie",
    typeTone: "purple",
    genre: "Romance",
    status: "Ready",
    dateAdded: "14 Apr 2026",
    views: "—",
    swatch: "#5D6024",
    description: "A romance feature set across a single night in Accra.",
    releaseDate: "14/04/2026",
    cast: "Nana Mensah, Ama K.",
    subtitleFile: "accra-by-night-en.srt",
  },
];
